### ISSUE TITLE
crit error on write

### ISSUE THREAD

**Issue by Teckiee** [PlopAndRun/Factorio-Memory-Cards#1]
The mod Memory cards (0.1.0) caused a non-recoverable error.
Please report this error to the mod author.

Error while running event memory-cards::on_tick (ID 0)
LuaItemStack API call when LuaItemStack was invalid for read.
stack traceback:
	[C]: in function 'set_tag'
	__memory-cards__/control/memorycard.lua:51: in function 'save_data'
	__memory-cards__/control/writer.lua:92: in function 'on_tick'
	__memory-cards__/control.lua:38: in function <__memory-cards__/control.lua:37>
	
	
Seems to be when the writer starts writing a second card when there's still a card in the output slot.

**Comment by PlopAndRun** [comment]
That's weird... do you remember what did you do?

**Comment by PlopAndRun** [comment]
Ah, never mind, I've reproduced it

**Comment by PlopAndRun** [comment]
Such an unfortunate bug. I cannot change the output stack while a recipe is running, but there is no tick when the recipe is not running when there is enough input items. 

Fixed the crash but I hope to find a better solution
